version: "3"
services:
  energy-investment-data:
    image: energy-investment-data
    ports:
      - "8045:8011"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/renewable_energy?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: "root"
      SPRING_DATASOURCE_PASSWORD: "root"
    build:
      context: "./"
      dockerfile: "Dockerfile"
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=root
      - MYSQL_DATABASE=renewable_energy


